"""New vers auth

Revision ID: a1b6b8781dbf
Revises: f1e477c90c5d
Create Date: 2024-09-02 18:01:52.060864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b6b8781dbf'
down_revision: Union[str, None] = 'f1e477c90c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'register_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'registered_at')
    # ### end Alembic commands ###
